apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: nginx-pod
      namespace: nginx
      labels: 
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx:latest
