apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-notes-app-deployment
  namespace: django-notes-app
  labels:
    app: django-notes-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-notes-app
  template:
    metadata:
      labels:
        app: django-notes-app
    spec:
      containers:
      - name: django-notes-app
        image: ayushrathore09/my-app:latest
        ports:
        - containerPort: 8000
