kind: Service
apiVersion: v1
metadata:
  name: django-notes-app-service
  namespace: django-notes-app
spec:
  selector:
    app: django-notes-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
