apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: apache-vpa
  namespace: apache
spec:
  targetRef:
    name: apache-deployment
    kind: Deployment
    apiVersion: apps/v1
  updatePolicy:
    updateMode: "Auto"  
  
